sudo: required
services:
  - docker
notifications: false

before_install:
- docker pull probonopd/docker-build-subsurface
- # docker run probonopd/docker-build-subsurface /bin/bash -c 'export NO_DOWNLOAD=1 ; bash -ex /subsurface.centos6.sh'
- docker run probonopd/docker-build-subsurface /bin/bash -ex /subsurface.centos6.sh

script:
- docker cp $(docker ps -alq):/Subsurface/ .
- ls -lh Subsurface/
- wget -c https://raw.githubusercontent.com/probonopd/travis2github/master/travis2github.py
- wget -c https://raw.githubusercontent.com/probonopd/travis2github/master/magic.py
- python travis2github.py Subsurface/*.AppImage
