sudo: required
services:
- docker
notifications:
- email: false

before_install:
- # Install prerequisites for travis2github.py uploader
- wget -c https://raw.githubusercontent.com/probonopd/travis2github/master/travis2github.py
- wget -c https://raw.githubusercontent.com/probonopd/travis2github/master/magic.py
- sudo apt-get update -qq
- sudo apt-get install python-requests  python-chardet python-urllib3 python-six -qq
- ln -s /usr/lib/python2.7/dist-packages/six.py /usr/lib/python2.7/dist-packages/requests/ /usr/lib/python2.7/dist-packages/chardet/ /usr/lib/python2.7/dist-packages/urllib3/ .

script:
- wget https://github.com/probonopd/AppImages/raw/master/recipes/subsurface.centos6.sh # Get more recent script than in container
- docker cp subsurface.centos6.sh probonopd/docker-build-subsurface:/subsurface.centos6.sh # Copy in more recent script
- docker run probonopd/docker-build-subsurface /bin/bash -ex /subsurface.centos6.sh
- docker cp $(docker ps -alq):/Subsurface/ .
- ls -lh Subsurface/
- python travis2github.py Subsurface/*.AppImage
