sudo: required
services:
  - docker
notifications:
email: false

before_install:
- wget -c https://raw.githubusercontent.com/probonopd/travis2github/master/travis2github.py
- wget -c https://raw.githubusercontent.com/probonopd/travis2github/master/magic.py
- sudo apt-get update -qq
- sudo apt-get install python-requests  python-chardet python-urllib3 python-six -qq
- ln -s /usr/lib/python2.7/dist-packages/six.py /usr/lib/python2.7/dist-packages/requests/ /usr/lib/python2.7/dist-packages/chardet/ /usr/lib/python2.7/dist-packages/urllib3/ .

script:
- docker run probonopd/docker-build-subsurface /bin/bash -c 'export NO_DOWNLOAD=1 ; bash -ex /subsurface.centos6.sh'
- #docker run probonopd/docker-build-subsurface /bin/bash -ex /subsurface.centos6.sh
- docker cp $(docker ps -alq):/Subsurface/ .
- ls -lh Subsurface/
- python travis2github.py Subsurface/*.AppImage
