sudo: false
addons:
  apt:
    packages:
    - bsdtar
    - curl
services:
- docker

env:
  - RECIPE=scribus
  - RECIPE=subsurface
  - RECIPE=firefox

script:
#- mkdir -p ./out/
#- wget https://raw.githubusercontent.com/probonopd/AppImages/master/recipes/$RECIPE/Recipe -O ./out/Recipe
#- sed -i -e 's|sudo ||g' ./out/Recipe # For subsurface recipe
#- docker run -i -v ${PWD}/out:/out probonopd/appimages:$RECIPE /bin/bash -ex /out/Recipe
#- ls -lh out/*.AppImage
- bash travis.sh $RECIPE
- find out/ -name "*.AppImage" -exec bash bintray.sh {} \; 
