sudo: required
dist: trusty
addons:
  apt:
    packages:
    - bsdtar
    - curl
    - zsync
    - squashfs-tools
services:
- docker

env:
  - RECIPE=leafpad

script:
- bash -e travis.sh $RECIPE
- find out/ -name "*.AppImage" -exec bash -e bintray.sh {} \; 

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4bf20518805a55998cc2
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always
