sudo: false
addons:
  apt:
    packages:
    - bsdtar
    - curl
    - zsync
services:
- docker

env:
#  - RECIPE=scribus
#  - RECIPE=subsurface
#  - RECIPE=firefox
#  - RECIPE=arduino
#  - RECIPE=libreoffice
#  - RECIPE=vlc
  - RECIPE=leafpad
#  - RECIPE=chromium

script:
- bash travis.sh $RECIPE
- find out/ -name "*.AppImage" -exec bash -e bintray.sh {} \; 

notifications:
irc:
channels:
- "chat.freenode.net#$RECIPE"
template:
- "https://github.com/probonopd/AppImages/blob/master/recipes/$RECIPE/Recipe: %{build_url}: %{message}"
- "Change view : %{compare_url}"
on_success: always
