sudo: false
addons:
  apt:
    packages:
    - bsdtar
    - curl
services:
- docker

env:
#  - RECIPE=scribus
#  - RECIPE=subsurface
#  - RECIPE=firefox
  - RECIPE=arduino

script:
- bash travis.sh $RECIPE
- find out/ -name "*.AppImage" -exec bash bintray.sh {} \; 
