sudo: required
services:
  - docker
notifications: false

before_install:
- docker pull probonopd/docker-build-subsurface
- docker run probonopd/docker-build-subsurface /bin/bash -ex subsurface.centos6.sh
- docker ps -a

script:
- docker cp $(docker ps -alq):/Subsurface/Subsurface-*.AppImage .
- ls -lh .
- find /var/ -name *.AppImage
