sudo: required
services:
- docker
- notifications: false

env:
  - RECIPE=scribus
  
before_install:
- # Install prerequisites for travis2github.py uploader
- wget -c https://raw.githubusercontent.com/probonopd/travis2github/master/travis2github.py
- wget -c https://raw.githubusercontent.com/probonopd/travis2github/master/magic.py
- sudo apt-get update -qq
- sudo apt-get install python-requests  python-chardet python-urllib3 python-six -qq
- ln -s /usr/lib/python2.7/dist-packages/six.py /usr/lib/python2.7/dist-packages/requests/ /usr/lib/python2.7/dist-packages/chardet/ /usr/lib/python2.7/dist-packages/urllib3/ .

script:
- mkdir -p ./mnt/
- wget https://raw.githubusercontent.com/probonopd/AppImages/master/recipes/$RECIPE/Recipe -o ./mnt/Recipe
- docker --version
- docker run -i -v ${PWD}/mnt:/mnt probonopd/appimages:$RECIPE /bin/bash -ex /mnt/Recipe
- docker cp $(docker ps -alq):/out/ . # To be replaced by using /mnt
- python travis2github.py out/*.AppImage
